"""required board author_id

Revision ID: 1ee05e36e59b
Revises: 676a1842e452
Create Date: 2026-09-18 11:09:15.789159

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ee05e36e59b"
down_revision: str | Sequence[str] | None = "676a1842e452"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("boards", "author_id", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("boards", "author_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###
