"""add board_list, card, label, comments; add author_id for workspaces, boards, list, cards

Revision ID: 676a1842e452
Revises: 997bfc85daa2
Create Date: 2026-09-17 17:27:29.647760

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "676a1842e452"
down_revision: str | Sequence[str] | None = "997bfc85daa2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    enum_changes = {
        "boardstatus": ("ACTIVE", "ARCHIVED"),
        "boardview": ("BOARD", "TABLE"),
        "boardrole": ("MEMBER", "ADMIN", "VIEWER"),
    }

    for enum_name, values in enum_changes.items():
        for value in values:
            op.execute(f"ALTER TYPE {enum_name} RENAME VALUE '{value}' TO '{value.lower()}'")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "board_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=10), nullable=True),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "archived", name="boardliststatus"),
            server_default="active",
            nullable=False,
        ),
        sa.Column(
            "workflow_status",
            sa.Enum("todo", "in_progress", "review", "done", name="listworkflowstatus"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("board_id", "order", name="uq_board_board_list_order"),
    )
    op.create_table(
        "labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("color", sa.String(length=10), nullable=True),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("list_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("low", "medium", "high", "urgent", name="cardpriority"),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum("active", "archived", name="cardstatus"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("start_date", sa.DateTime(), nullable=True),
        sa.Column("due_date", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["list_id"], ["board_lists.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("list_id", "order", name="uq_board_list_card_order"),
    )
    op.create_table(
        "card_labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("label_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["label_id"], ["labels.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("card_id", "label_id", name="uq_cards_labels"),
    )
    op.create_table(
        "card_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column(
            "assigned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("card_id", "user_id", name="uq_card_members_user"),
    )
    op.create_table(
        "comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["author_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_unique_constraint(
        "uq_board_members_board_user", "board_members", ["board_id", "user_id"]
    )
    op.add_column("boards", sa.Column("author_id", sa.Integer(), nullable=True))
    op.alter_column(
        "boards",
        "description",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.create_foreign_key(
        "fk_boards_author_id_users", "boards", "users", ["author_id"], ["id"], ondelete="RESTRICT"
    )
    op.alter_column(
        "workspaces",
        "owner_id",
        new_column_name="author_id",
        existing_type=sa.Integer(),
        existing_nullable=False,
    )
    op.alter_column(
        "workspaces",
        "description",
        existing_type=sa.VARCHAR(length=1000),
        type_=sa.Text(),
        existing_nullable=True,
    )
    op.alter_column("boards", "status", server_default=sa.text("'active'"))
    op.alter_column("boards", "view", server_default=sa.text("'board'"))
    op.alter_column("board_members", "role", server_default=sa.text("'member'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("boards", "status", server_default=None)
    op.alter_column("boards", "view", server_default=None)
    op.alter_column("board_members", "role", server_default=None)

    enum_changes = {
        "boardstatus": ("active", "archived"),
        "boardview": ("board", "table"),
        "boardrole": ("member", "admin", "viewer"),
    }

    for enum_name, values in enum_changes.items():
        for value in values:
            op.execute(f"ALTER TYPE {enum_name} RENAME VALUE '{value}' TO '{value.upper()}'")
    op.alter_column(
        "workspaces",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=True,
    )
    op.alter_column(
        "workspaces",
        "author_id",
        new_column_name="owner_id",
        existing_type=sa.Integer(),
        existing_nullable=False,
    )
    op.drop_constraint("fk_boards_author_id_users", "boards", type_="foreignkey")
    op.alter_column(
        "boards",
        "description",
        existing_type=sa.Text(),
        type_=sa.VARCHAR(length=1000),
        existing_nullable=True,
    )
    op.drop_column("boards", "author_id")
    op.drop_constraint("uq_board_members_board_user", "board_members", type_="unique")
    op.drop_table("comments")
    op.drop_table("card_members")
    op.drop_table("card_labels")
    op.drop_table("cards")
    op.drop_table("labels")
    op.drop_table("board_lists")
    for enum_name in (
        "cardstatus",
        "cardpriority",
        "listworkflowstatus",
        "boardliststatus",
    ):
        postgresql.ENUM(name=enum_name).drop(
            op.get_bind(),
            checkfirst=True,
        )
    # ### end Alembic commands ###
