"""add model: boards and board_members

Revision ID: 997bfc85daa2
Revises: 55df1d11ddb9
Create Date: 2026-09-09 18:09:06.631130

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "997bfc85daa2"
down_revision: str | Sequence[str] | None = "55df1d11ddb9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    workspace_role = postgresql.ENUM(
        "member",
        "admin",
        "owner",
        name="workspacerole",
    )

    workspace_role.create(op.get_bind(), checkfirst=True)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boards",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("workspace_id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("status", sa.Enum("ACTIVE", "ARCHIVED", name="boardstatus"), nullable=False),
        sa.Column("view", sa.Enum("BOARD", "TABLE", name="boardview"), nullable=False),
        sa.ForeignKeyConstraint(["workspace_id"], ["workspaces.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "board_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("board_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.Enum("MEMBER", "ADMIN", "VIEWER", name="boardrole"), nullable=False),
        sa.Column(
            "joined_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(["board_id"], ["boards.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column(
        "workspace_members",
        "role",
        existing_type=sa.VARCHAR(length=20),
        type_=workspace_role,
        existing_nullable=False,
        postgresql_using="lower(role)::workspacerole",
    )
    op.alter_column(
        "workspace_members",
        "role",
        server_default=sa.text("'member'::workspacerole"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    workspace_role = postgresql.ENUM(
        "member",
        "admin",
        "owner",
        name="workspacerole",
        create_type=False,
    )

    op.alter_column(
        "workspace_members",
        "role",
        existing_type=workspace_role,
        type_=sa.VARCHAR(length=20),
        existing_nullable=False,
        server_default=None,
        postgresql_using="role::text",
    )

    workspace_role.drop(op.get_bind(), checkfirst=True)

    op.drop_table("board_members")
    op.drop_table("boards")
    # ### end Alembic commands ###
